export enum DamageGroups {
  piercing = "piercing",
  slashing = "slashing",
  bludgeon = "bludgeon",
  toxic = "toxic",
  fire = "fire",
  hrg_teslauncher_dot = "hrg_teslauncher_dot",
  hrg_teslauncher = "hrg_teslauncher",
  microwave = "microwave",
  explosives = "explosives",
  rpg7_impact = "rpg7_impact",
  freeze = "freeze",
  shells = "shells",
  bleeding = "bleeding",
  emp = "emp",
  submachine = "submachine",
  assault_rifle = "assault_rifle",
  shotgun = "shotgun",
  handgun = "handgun",
  rifle = "rifle",
  ballistic_hemogoblin = "ballistic_hemogoblin",
}
